/*
 *     ICE (Interval Calculator for Engineer) is a programmable calculator working on intervals.
 *     Copyright (C) 2009  Simone Pernice
 * 
 *     This program is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU General Public License as published by
 *     the Free Software Foundation, either version 3 of the License, or
 *     (at your option) any later version.
 * 
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 * 
 *     You should have received a copy of the GNU General Public License
 *     along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * ConsoleEngCalculatorHistoryEditor.java
 *
 * Created on Sep 29, 2011, 10:37:00 PM
 */

package engcalculatorConsole.ecInput;

import engcalculatorConsole.findReplace.EngCalculatorConsoleReplace;
import engcalculatorConsole.findReplace.EngCalculatorConsoleFind;
import engcalculatorConsole.iceJTextArea.ICEJTextArea;
import engcalculator.AsynchronousOutput;
import engcalculatorConsole.EngCalculatorConsoleMainFrame;
import javax.swing.JDialog;
import javax.swing.JTextArea;

/**
 *
 * @author Simone Pernice <pernice@libero.it>
 */
public final class EngCalculatorConsoleInputEditor extends javax.swing.JDialog implements AsynchronousOutput{
    private final EngCalculatorConsoleMainFrame eccmfParent;
    private final JTextArea mainFrameInputText;
    private JDialog replaceBox, findBox;    

    /** Creates new form ConsoleEngCalculatorHistoryEditor */
    public EngCalculatorConsoleInputEditor(java.awt.Frame parent, boolean modal, EngCalculatorConsoleMainFrame eccmfParent, JTextArea inputText) {
        super(parent, modal);
        setLocationRelativeTo(parent);
        initComponents();
        this.eccmfParent = eccmfParent;
        this.mainFrameInputText = inputText;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCancel = new javax.swing.JButton();
        jButtonDeleteAll = new javax.swing.JButton();
        jButtonOK = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaInput = new ICEJTextArea (this, null);
        jButtonExec = new javax.swing.JButton();
        jButtonFind = new javax.swing.JButton();
        jButtonReplace = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaHelp = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(engcalculatorConsole.EngCalculatorConsoleApp.class).getContext().getResourceMap(EngCalculatorConsoleInputEditor.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        jButtonCancel.setMnemonic('C');
        jButtonCancel.setText(resourceMap.getString("jButtonCancel.text")); // NOI18N
        jButtonCancel.setName("jButtonCancel"); // NOI18N
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jButtonDeleteAll.setText(resourceMap.getString("jButtonDeleteAll.text")); // NOI18N
        jButtonDeleteAll.setName("jButtonDeleteAll"); // NOI18N
        jButtonDeleteAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteAllActionPerformed(evt);
            }
        });

        jButtonOK.setMnemonic('O');
        jButtonOK.setText(resourceMap.getString("jButtonOK.text")); // NOI18N
        jButtonOK.setName("jButtonOK"); // NOI18N
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTextAreaInput.setColumns(20);
        jTextAreaInput.setFont(resourceMap.getFont("jTextAreaInput.font")); // NOI18N
        jTextAreaInput.setRows(5);
        jTextAreaInput.setName("jTextAreaInput"); // NOI18N
        jScrollPane1.setViewportView(jTextAreaInput);

        jButtonExec.setText(resourceMap.getString("jButtonExec.text")); // NOI18N
        jButtonExec.setName("jButtonExec"); // NOI18N
        jButtonExec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExecActionPerformed(evt);
            }
        });

        jButtonFind.setMnemonic('C');
        jButtonFind.setText(resourceMap.getString("jButtonFind.text")); // NOI18N
        jButtonFind.setName("jButtonFind"); // NOI18N
        jButtonFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFindActionPerformed(evt);
            }
        });

        jButtonReplace.setMnemonic('C');
        jButtonReplace.setText(resourceMap.getString("jButtonReplace.text")); // NOI18N
        jButtonReplace.setName("jButtonReplace"); // NOI18N
        jButtonReplace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReplaceActionPerformed(evt);
            }
        });

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        jTextAreaHelp.setEditable(false);
        jTextAreaHelp.setColumns(20);
        jTextAreaHelp.setLineWrap(true);
        jTextAreaHelp.setRows(5);
        jTextAreaHelp.setName("jTextAreaHelp"); // NOI18N
        jScrollPane2.setViewportView(jTextAreaHelp);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonDeleteAll)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonFind)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonReplace)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonExec)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonOK)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancel)
                    .addComponent(jButtonOK)
                    .addComponent(jButtonDeleteAll)
                    .addComponent(jButtonExec)
                    .addComponent(jButtonFind)
                    .addComponent(jButtonReplace))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
        storeInput();
        setVisible(false);
    }//GEN-LAST:event_jButtonOKActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonDeleteAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteAllActionPerformed
        jTextAreaInput.setText("");
    }//GEN-LAST:event_jButtonDeleteAllActionPerformed

    private void jButtonExecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExecActionPerformed
        storeInput();
        eccmfParent.evaluateLine();
        jTextAreaInput.setText("");
    }//GEN-LAST:event_jButtonExecActionPerformed

    private void jButtonFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFindActionPerformed
        if (findBox == null) findBox = new EngCalculatorConsoleFind(jTextAreaInput, this);
        findBox.setVisible(true);
    }//GEN-LAST:event_jButtonFindActionPerformed

    private void jButtonReplaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReplaceActionPerformed
        if (replaceBox == null) replaceBox = new EngCalculatorConsoleReplace(jTextAreaInput, this);
        replaceBox.setVisible(true);
    }//GEN-LAST:event_jButtonReplaceActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonDeleteAll;
    private javax.swing.JButton jButtonExec;
    private javax.swing.JButton jButtonFind;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JButton jButtonReplace;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaHelp;
    private javax.swing.JTextArea jTextAreaInput;
    // End of variables declaration//GEN-END:variables

    public void setVisible () {
        jTextAreaInput.setText(mainFrameInputText.getText());        
        jTextAreaInput.setCaretPosition(mainFrameInputText.getCaretPosition());
        ((ICEJTextArea) jTextAreaInput).clearUndo();
        setVisible(true);
        jTextAreaInput.requestFocusInWindow();
    }

    private void storeInput () {
        mainFrameInputText.setText(jTextAreaInput.getText());
        mainFrameInputText.setCaretPosition(jTextAreaInput.getCaretPosition());
    }    
    
    public void printOnOutputAreaInRegular(String output) {
        printOnHelpArea (output);
    }

    public void printOnOutputAreaInBold(String output) {
        printOnHelpArea (output);
    }

    public void printOnOutputAreaInItalic(String output) {
        printOnHelpArea (output);
    }
    
    private void printOnHelpArea (String txt) {
        jTextAreaHelp.setText(txt);
    }
    
}
